functions/index.js

using the lastLesson parameter on course DB to verify if the lesson sent is the last lesson and allows to mintNFT continue.

[127]: Check if its the course last lesson

---

components/Card/index.js
pages/courses/index.js

Screenshots:
mobile
much tags (I hardcoded more tags just to test)
inactive
medium screen
wide screen

Fix: Courses Card responsivity

---

components/ThemeSwitch/index.js

Making cursor pointer on ThemeSwitch button

---

components/Home/Inovadoras-nft-collection/Cover/index.js
components/Home/Inovadoras-nft-collection/index.js
pages/nft-collection-para-elas/index.js

Need change images in :
components/home/Inovadoras-nft-collection/Cover/index.js
pages/nft-collection-para-elas/index.js line 26

[feat]: Specif Page, url, cover (nft-collection-inovadoras)

---

components/Button/index.js
components/LoginButton/index.js

Small style refactor to items hover css upscale

[style] refactor hover scale amount value

---

pages/courses/index.js

Fix problem of courses page, courses cards too much big !

[style] ajust how to courses be displayed

---

components/Navbar/index.js

I record a [video](https://www.youtube.com/watch?v=M3L1vp3LycM) to see all changes

fix/refactor and re-design of navbar

---

components/Card/GeneralInfo/PersonalData/index.js
components/Card/GeneralInfo/ProfileFooter/index.js
components/Card/GeneralInfo/SocialData/index.js
tailwind.config.js

The profile page current on production : 
After ajusts :

[style] re-design profile page

---

components/Card/ShareLink/index.js
lib/dateFormat.js
pages/courses/[id].js

I create a option to the user register a event off a bootcamp on google calendar, the event is generated from url and i put the date of kickoff on url

Google calendar share

---

pages/404.js
pages/_app.js
pages/admin/createcohort.js
pages/admin/stats.js
pages/auth/index.js
pages/auth/signup/index.js
pages/courses/[id].js
pages/courses/[id]/lessons/[lesson].js
pages/courses/index.js
pages/index.js
pages/nft-collection-para-elas/index.js
pages/profile/index.js
pages/solidity-para-elas/index.js

Next.js have a default pages component named `_app.js` and this component is rendered in all routes by pages.
Based in this feature, i'm import navbar/footer on `_app.js` and remove all imports on pages components !

[Refactor] render of navbar/footer 

---

components/Modal/index.js
pages/courses/[id]/lessons/[lesson].js

This fix refear this bug :
Final adjust :

[fix] adjust overflow in CSS content

---

components/Home/index.js
pages/_app.js

This fix refear this css style :
Whit final ajust :

[fix]css-overflow on cookieNotice

---

pages/courses/[id]/lessons/[lesson].js

Improve Ux of Submit Lesson :
Before : 
After :

[fix] Ajust button submission lesson

---

components/Home/Cover/index.js
components/Home/index.js

Updating home and text to redirect to GPT3_Writer build;

Gpt build update

---

components/Navbar/index.js
pages/tasks/index.js
seed-data.json

[Issue 164](https://github.com/w3b3d3v/web3-bootcamp-platform/issues/164)

[FEATURE] - Implementation of task page

---

pages/courses/[id]/[section]/[lesson].js

Fix bug of youtube iframes not showing for youtube link variations like yout.be/VIDEO_ID

fix: Youtube iFrame not showing

---

OnChain/.gitignore
OnChain/README.md
OnChain/contracts/Web3DevNFT.sol
OnChain/contracts/transparent_upgradeable/Demo.sol
OnChain/contracts/transparent_upgradeable/DemoV2.sol
OnChain/contracts/transparent_upgradeable/Proxies.sol
OnChain/hardhat.config.ts
OnChain/ignition/modules/ProxyModule.ts
OnChain/ignition/modules/Web3DevNFTModule.ts
OnChain/ignition/modules/transparent_upgradeable/DemoModule.ts
OnChain/ignition/modules/transparent_upgradeable/DemoV2Module.ts
OnChain/ignition/modules/transparent_upgradeable/ProxyModule.ts
OnChain/ignition/modules/transparent_upgradeable/UpgradeModule.ts
OnChain/package-lock.json
OnChain/package.json
OnChain/test/proxy.test.ts
OnChain/tsconfig.json

creating proxy NFT contract
This pull request introduces a new feature: a Hardhat project structured using Ignition for deployment, with Solidity version 0.8.24. The core of this feature is an NFT that represents all activities a user has performed on Web3Dev.

feat: creating Onchain structure for Web3Dev NFT task

---

functions/email_templates/nft_delivery.js
functions/emails.js
functions/index.js
functions/lib/checkUserLessons.js
functions/lib/nft_mints.js

1. **Language Sections Lesson Checks**: Improved the logic for checking lessons within different language sections and updated the associated queries for better accuracy.
2. **Email Copy Update for NFT Campaign**: Revised the email copy used in our NFT campaign to ensure clearer communication and better engagement with recipients.

Fix NFT mint process

---

components/Card/GeneralInfo/PersonalData/index.spec.js
components/Card/GeneralInfo/ProfessionalData/index.js
components/Card/GeneralInfo/ProfileFooter/index.spec.js
components/Card/GeneralInfo/SocialData/index.js
components/Card/GeneralInfo/SocialData/index.spec.js
components/Card/GeneralInfo/index.js
components/Card/GeneralInfo/index.spec.js
components/Footer/index.spec.js
components/LoginButton/index.js
components/Tabs/index.spec.js
components/ThemeSwitch/index.js
components/ThemeSwitch/index.spec.js
jest.config.js
lib/lessons.spec.js
lib/sections.spec.js

Fix unit tests

---

components/Card/Issue/index.js
components/IssueCard/index.js
components/Modal/ModalTask/index.js
lib/user.js
pages/tasks/index.js
seed-data.json

When a user clicks "Apply," the following actions should take place:
Check GitHub Connection:
Verify if the user has connected their GitHub account.
If not, redirect them to the GitHub connection URL.

Feat/Apply Button -> Github Integration

---

components/Card/StudyGroup/index.js
firebase.json
next.config.js
pages/admin/createGroup.js
pages/admin/editGroup.js
pages/study-groups/[slug].js
public/locales/pt-BR/translation.json
storage.rules

- Page created to edit current study groups.
- Deactivated StudyGroups removed from listing.

Study Group Fixes

---

components/Card/Issue/index.js
lib/user.js
lib/utils/constants.js
pages/tasks/index.js
public/locales/en/translation.json
public/locales/pt-BR/translation.json

Making task description accept markdown
[Screencast from 27-08-2024 15:18:03.webm](https://github.com/user-attachments/assets/4525ecb3-b6d8-4feb-b07b-0e7271b29932)

deleting duplicate code and markdown tasks

---

components/Card/Issue/index.js
components/Filter/index.js
components/Navbar/index.js
components/SortBar/index.js
components/SortBar/utils.js
pages/tasks/index.js
public/locales/en/translation.json
public/locales/pt-BR/translation.json
seed-data.json

I made the sortbar work in a generic way where it is possible to use this component in another part of the application.

SortBar Should work for any metadata
